### ISSUE TITLE
Turning off "Can Snap Back" breaks grabbing in build mode

### ISSUE THREAD

**Issue by A1igator** [MephestoKhaan/HandPosing#24]
The grabbed object will simply ignore the grabber. You can recreate it by building the example scene provided in the repo. The cylinder and physics based lever will not work properly. It woks perfectly in play mode, just not when you build. I'm using unity 2019.4 and didn't change anything in the repo.(outside adding oculus integration asset)

**Comment by MephestoKhaan** [comment]
Thanks for the report! I will check it out later today

**Comment by MephestoKhaan** [comment]
Just testing this on PC with a build. Certainly the Cylinder and the Lever  are doing something wrong in build, as the grab never starts, the hand simply snaps.

**Comment by MephestoKhaan** [comment]
Fixed for now @A1igator  .

The problem was the Grabber was being called AFTER the snapper in builds. For now I put it in Update and LateUpdate respectively but will find a more robust solution when I have the time.

You can either pull the new fix or grab the package here: https://github.com/MephestoKhaan/HandPosing/releases/tag/0.1.1
